from dotenv import dotenv_values


creds = dotenv_values(".env")

API_VERSION = creds["API_VERSION"]

SECRET_KEY = creds["SECRET_KEY"]
ALGORITHM = creds["ALGORITHM"]
ACCESS_TOKEN_EXPIRE_MINUTES = int(creds["ACCESS_TOKEN_EXPIRE_MINUTES"])

DATABASE_HOST = creds["DATABASE_HOST"]
DATABASE_NAME = creds["DATABASE_NAME"]
DATABASE_USERNAME = creds["DATABASE_USERNAME"]
DATABASE_PASSWORD = creds["DATABASE_PASSWORD"]

TEST_DATABASE_NAME = creds["TEST_DATABASE_NAME"]

SQLALCHEMY_DATABASE_URL = f"postgresql://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{DATABASE_NAME}"
SQLALCHEMY_TEST_DATABASE_URL = f"postgresql://{DATABASE_USERNAME}:{DATABASE_PASSWORD}@{DATABASE_HOST}/{TEST_DATABASE_NAME}"

REDIS_HOST = creds["REDIS_HOST"]
REDIS_PORT = creds["REDIS_PORT"]
REDIS_DB = creds["REDIS_DB"]

REDIS_DB_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"


